spring:
  application:
    name: CardWithClue
  profiles:
    active: @profiles@

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:${graph.proj-path}/db/index.db
    druid:
      username:
      password:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: -1
      validation-query: SELECT '1' from sqlite_master
      validation-query-timeout: 3
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat
  ## https://blog.csdn.net/kfashfasf/article/details/136394399
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: none

