DROP TABLE IF EXISTS DATA_CARD;
CREATE TABLE DATA_CARD
(
    ID         INTEGER PRIMARY KEY AUTOINCREMENT,
    CARD_GROUP TEXT NOT NULL,
    CARD_KEY   TEXT NOT NULL,
    CARD_LINK  TEXT,
    CARD_DESC  TEXT
);

CREATE INDEX INDEX_DATA_CARD_GROUP ON DATA_CARD (CARD_GROUP);

INSERT INTO DATA_CARD(ID, CARD_KEY, CARD_GROUP, CARD_DESC)
VALUES (10000, 'SYSTEM - AUTO STARTER', 'UNKNOWN', '自动编号起始位置')

DROP TABLE IF EXISTS DATA_CLUE;
CREATE TABLE DATA_CLUE
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    CLUE_SOURCE INTEGER NOT NULL,
    CLUE_TARGET INTEGER NOT NULL,
    CLUE_GROUP  TEXT    NOT NULL,
    CLUE_TIME   DATETIME,
    CLUE_KEY    TEXT    NOT NULL,
    CLUE_LINK   TEXT,
    CLUE_DESC   TEXT
);
CREATE INDEX INDEX_DATA_CLUE_GROUP ON DATA_CLUE (CLUE_TIME);