DROP TABLE IF EXISTS DATA_CARD;
CREATE TABLE DATA_CARD
(
    ID              INTEGER PRIMARY KEY AUTOINCREMENT,
    CARD_GROUP      TEXT NOT NULL,
    CARD_KEY        TEXT NOT NULL,
    CARD_ANNOTATION TEXT,
    CARD_TIME       TEXT,
    CARD_ALIAS      TEXT,
    CARD_LINK       TEXT,
    CARD_DESC       TEXT,
    CARD_JSON       TEXT,
    UNIQUE (CARD_GROUP, CARD_KEY, CARD_ANNOTATION)
);
CREATE INDEX INDEX_DATA_CARD_GROUP ON DATA_CARD (CARD_GROUP);

DROP TABLE IF EXISTS DATA_CLUE;
CREATE TABLE DATA_CLUE
(
    ID         TEXT PRIMARY KEY,
    CLUE_GROUP TEXT    NOT NULL,
    SOURCE     INTEGER NOT NULL,
    TARGET     INTEGER NOT NULL,
    CLUE_KEY   TEXT,
    CLUE_TIME  TEXT,
    CLUE_ALIAS TEXT,
    CLUE_LINK  TEXT,
    CLUE_DESC  TEXT,
    CLUE_JSON  TEXT,
    UNIQUE (CLUE_GROUP, SOURCE, TARGET)
);
CREATE INDEX INDEX_DATA_CLUE_GROUP ON DATA_CLUE (CLUE_GROUP);